services:
  sfcast_cosmic_coding_sf7:
    container_name: sfcast_cosmic_coding_sf7
    image: php-8.3
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./backend:/app:delegated
    expose:
      - 9000

  sfcast_cosmic_coding_nginx:
    container_name: sfcast_cosmic_coding_nginx
    image: nginx:1.28
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend:/app:ro
    restart: unless-stopped