services:
  sfcast_cosmic_coding_sf7:
    container_name: sfcast_cosmic_coding_sf7
    image: php-8.3
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./backend:/app:delegated
    expose:
      - 9000

  sfcast_cosmic_coding_nginx:
    container_name: sfcast_cosmic_coding_nginx
    image: nginx:1.28
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend:/app:ro
    restart: unless-stopped

  sfcast_cosmic_coding_postgres:
    container_name: sfcast_cosmic_coding_postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: cosmiccoding_db
      POSTGRES_PASSWORD: cosmiccoding_p
      POSTGRES_USER: cosmiccoding_u
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "cosmiccoding_db", "-U", "cosmiccoding_u"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - sfcast_cosmic_coding_database_data:/var/lib/postgresql/data:rw

volumes:
  sfcast_cosmic_coding_database_data: